spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT} # environment variable
      storage:
        blob:
          account-name: ${AZURE_STORAGE_ACCOUNT_NAME} # environment variable
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  datasource:
    url: ${datasource-url} # secret from Azure Key Vault
    username: ${datasource-username} # secret from Azure Key Vault
    password: ${datasource-password} # secret from Azure Key Vault
  jpa:
    hibernate:
      ddl-auto: none # Turn off the DDL auto generation
ai:
  groq:
    endpoint: ${AI_GROQ_ENDPOINT:https://api.groq.com/openai/v1/chat/completions} # environment variable with default value
    api-key: ${ai-groq-api-key:your-groq-api-key} # environment variable with default value
