spring:
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: sa
    password:
  jpa:
    show-sql: true
  cloud:
    azure:
      storage:
        account-name: ${AZURE_STORAGE_ACCOUNT_NAME:YOUR_STORAGE_ACCOUNT_NAME} # environment variable with default value
        account-key: ${AZURE_STORAGE_ACCOUNT_KEY:YOUR_STORAGE_ACCOUNT_KEY} # environment variable with default value
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  data:
    redis:
      host: localhost
      port: 6379
ai:
  groq:
    endpoint: ${AI_GROQ_ENDPOINT:https://api.groq.com/openai/v1/chat/completions} # environment variable with default value
    api-key: ${AI_GROQ_API_KEY:YOUR_API_KEY} # environment variable with default value