spring:
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: sa
    password:
  jpa:
    show-sql: true
ai:
  groq:
    endpoint: ${AI_GROQ_ENDPOINT:https://api.groq.com/openai/v1/chat/completions} # environment variable with default value
    api-key: ${AI_GROQ_API_KEY:YOUR_API_KEY} # environment variable with default value